// sooindustry-angular/src/app/shared/navbar/navbar.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';
import { Location } from '@angular/common';

@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss'],
    standalone: false
})
export class NavbarComponent implements OnInit {
  private toggleButton: HTMLElement | null = null;
  private sidebarVisible: boolean = false;

  constructor(public location: Location, private element: ElementRef) {
    this.sidebarVisible = false;
  }

  ngOnInit(): void {
    const navbar: HTMLElement = this.element.nativeElement;
    const toggleElements = navbar.getElementsByClassName('navbar-toggler');
    this.toggleButton = toggleElements.length > 0 ? toggleElements[0] as HTMLElement : null;
  }

  sidebarOpen(): void {
    if (!this.toggleButton) return;
    
    const html = document.getElementsByTagName('html')[0];
    
    setTimeout(() => {
      this.toggleButton?.classList.add('toggled');
    }, 500);
    
    html.classList.add('nav-open');
    this.sidebarVisible = true;
  }

  sidebarClose(): void {
    if (!this.toggleButton) return;
    
    const html = document.getElementsByTagName('html')[0];
    this.toggleButton.classList.remove('toggled');
    this.sidebarVisible = false;
    html.classList.remove('nav-open');
  }

  sidebarToggle(): void {
    if (this.sidebarVisible) {
      this.sidebarClose();
    } else {
      this.sidebarOpen();
    }
  }
  isHome(): boolean {
    let path = this.location.prepareExternalUrl(this.location.path());
    if (path.charAt(0) === '#') {
      path = path.slice(1);
    }
    return path === '/home';
  }
}

<nav class="navbar navbar-expand-lg fixed-top navbar-transparent" color-on-scroll="500">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" [routerLink]="['/home']"><img src="./assets/img/sooin-logo.gif">SOOIN Industry</a>
            <button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation" (click)="sidebarToggle()">
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse" id="navbarToggler" style="justify-content: flex-end;">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item" *ngIf="!isDocumentation()">
                    <a class="nav-link" rel="tooltip" data-placement="bottom" [routerLink]="['/about-us']">
                        <i class="nc-icon nc-alert-circle-i"></i>
                        회사소개
                    </a>
                </li>
                <li class="nav-item" *ngIf="!isDocumentation()">
                    <a class="nav-link" rel="tooltip" data-placement="bottom" [routerLink]="['/products']">
                        <i class="nc-icon nc-box"></i>
                        제품소개
                    </a>
                </li>
                <li class="nav-item" *ngIf="!isDocumentation()">
                    <a class="nav-link" rel="tooltip" data-placement="bottom" [routerLink]="['/customer-support']">
                        <i class="nc-icon nc-satisfied"></i>
                        고객지원
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

// sooindustry-react/src/app/_components/navbar.tsx
/* eslint-disable @next/next/no-img-element */
"use client";

import clsx from "clsx";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { navLinks } from "@/data/navigation";

export function Navbar() {
  const pathname = usePathname();
  const [expanded, setExpanded] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    setExpanded(false);
  }, [pathname]);

  useEffect(() => {
    const handleScroll = () => {
      const isNowScrolled = window.scrollY > 40;
      setScrolled((prev) => (prev === isNowScrolled ? prev : isNowScrolled));
    };

    handleScroll();
    window.addEventListener("scroll", handleScroll, { passive: true });

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const activeHrefSet = useMemo(() => {
    if (!pathname) {
      return new Set<string>();
    }
    const normalized = pathname === "/" ? "/home" : pathname;
    return new Set([normalized]);
  }, [pathname]);

  return (
    <nav
      className={clsx("navbar navbar-expand-lg fixed-top sooin-navbar", {
        "navbar-transparent": !scrolled,
        "navbar-solid": scrolled,
      })}
    >
      <div className="container">
        <div className="navbar-translate">
          <Link className="navbar-brand d-flex align-items-center gap-2" href="/home">
            <Image src="/img/sooin-logo.gif" alt="SOOIN Industry" width={40} height={26} />
            SOOIN Industry
          </Link>
          <button
            type="button"
            aria-label="Toggle navigation"
            aria-expanded={expanded}
            className={clsx("navbar-toggler navbar-burger", { toggled: expanded })}
            onClick={() => setExpanded((prev) => !prev)}
          >
            <span className="navbar-toggler-bar" />
            <span className="navbar-toggler-bar" />
            <span className="navbar-toggler-bar" />
          </button>
        </div>

        <div
          className={clsx("sooin-nav-collapse", { "is-open": expanded })}
          id="navbarToggler"
        >
          <ul className="navbar-nav">
            {navLinks.map((link) => (
              <li
                key={link.href}
                className={clsx("nav-item", {
                  active:
                    activeHrefSet.has(link.href) ||
                    (link.href !== "/home" && pathname?.startsWith(link.href)),
                })}
              >
                <Link className="nav-link d-flex align-items-center gap-2" href={link.href}>
                  <i className={link.icon} aria-hidden="true" />
                  {link.label}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </nav>
  );
}
