// sooindustry-angular/src/app/components/customer-support/customer-support.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-customer-support',
    templateUrl: './customer-support.component.html',
    styleUrls: ['./customer-support.component.scss'],
    standalone: false
})
export class CustomerSupportComponent {
  focus: boolean = false;
  focus1: boolean = false;
}

<div class="wrapper">
    <div class="page-header page-header-xs" data-parallax="true" style="background-image: url('./assets/img/general/misc-1.jpg');">
        <div class="filter"></div>
        <div class="content-center">
            <div class="container">
                <h1 class="title">연락처 및 고객지원</h1>
                <h4 class="description">수인산업과 함께하세요</h4>
            </div>
        </div>
    </div>

    <!-- 회사 연락처 정보 섹션 -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center mb-5">
                    <h2 class="title">연락처 정보</h2>
                    <h5 class="description">수인산업에 언제든지 문의해 주세요</h5>
                    <div class="separator-line"></div>
                </div>
            </div>
            
            <div class="row align-items-center">
                <div class="col-md-6 mb-4">
                    <div class="company-info-card">
                        <div class="card-header">
                            <h3 class="company-title">
                                <i class="nc-icon nc-building"></i>
                                수인산업
                            </h3>
                        </div>
                        <div class="card-body">
                            <div class="contact-info">
                                <div class="contact-item">
                                    <div class="contact-icon">
                                        <i class="nc-icon nc-single-02"></i>
                                    </div>
                                    <div class="contact-content">
                                        <strong>대표이사</strong>
                                        <span>김웅기</span>
                                    </div>
                                </div>
                                
                                <div class="contact-item">
                                    <div class="contact-icon">
                                        <i class="nc-icon nc-calendar-60"></i>
                                    </div>
                                    <div class="contact-content">
                                        <strong>설립일</strong>
                                        <span>2015년 09월 10일</span>
                                    </div>
                                </div>
                                
                                <div class="contact-item">
                                    <div class="contact-icon">
                                        <i class="nc-icon nc-trophy"></i>
                                    </div>
                                    <div class="contact-content">
                                        <strong>특허</strong>
                                        <span>진공로 실용신안 취득</span>
                                    </div>
                                </div>
                                
                                <div class="contact-item">
                                    <div class="contact-icon">
                                        <i class="nc-icon nc-settings-gear-65"></i>
                                    </div>
                                    <div class="contact-content">
                                        <strong>주요 사업</strong>
                                        <span>열처리 산업로 제작 전문</span>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="quick-contact-buttons mt-4">
                                <button class="btn btn-danger btn-round">
                                    <i class="nc-icon nc-mobile"></i>
                                    전화 문의
                                </button>
                                <button class="btn btn-outline-danger btn-round">
                                    <i class="nc-icon nc-email-85"></i>
                                    이메일 문의
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="contact-image-wrapper">
                        <img src="assets/img/general/customer-card.png" alt="고객관리카드" class="img-fluid rounded shadow">
                        <div class="image-overlay">
                            <div class="overlay-text">
                                <i class="nc-icon nc-check-2"></i>
                                <p>체계적인 고객 관리</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 주요 고객사 섹션 -->
    <div class="section section-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center mb-5">
                    <h2 class="title">주요 고객사</h2>
                    <h5 class="description">신뢰할 수 있는 파트너십</h5>
                    <div class="separator-line"></div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>마스터리스트</h5>
                        <p>열처리 전문업체</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>한성열처리</h5>
                        <p>금속 열처리 전문</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>영동써모텍</h5>
                        <p>써모 기술 전문</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>고려금형열처리</h5>
                        <p>금형 열처리 전문</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>한양종합열처리</h5>
                        <p>종합 열처리 서비스</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>대한열처리</h5>
                        <p>열처리 전문업체</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>동신금형열처리</h5>
                        <p>금형 전문 열처리</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>화성진공열처리</h5>
                        <p>진공 열처리 전문</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>하남열처리</h5>
                        <p>지역 열처리 전문</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>대우특수진공</h5>
                        <p>특수 진공 기술</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>영동금형열처리</h5>
                        <p>금형 열처리 솔루션</p>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="customer-card">
                        <div class="customer-icon">
                            <i class="nc-icon nc-settings-gear-65"></i>
                        </div>
                        <h5>오토테크인터내셔날</h5>
                        <p>국제 자동차 기술</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 문의 방법 섹션 -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center mb-5">
                    <h2 class="title">문의 방법</h2>
                    <h5 class="description">다양한 방법으로 연락하실 수 있습니다</h5>
                    <div class="separator-line"></div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="contact-method">
                        <div class="method-icon">
                            <i class="nc-icon nc-phone-2"></i>
                        </div>
                        <h4>전화 문의</h4>
                        <p>빠른 상담을 원하시면 전화로 연락하세요</p>
                        <div class="contact-details">
                            <div class="contact-detail-item">
                                <strong>TEL</strong>
                                <span>032-517-2473</span>
                            </div>
                            <div class="contact-detail-item">
                                <strong>FAX</strong>
                                <span>032-567-2473</span>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-4 mb-4">
                    <div class="contact-method">
                        <div class="method-icon">
                            <i class="nc-icon nc-email-85"></i>
                        </div>
                        <h4>이메일 문의</h4>
                        <p>자세한 문의사항은 이메일로 보내주세요</p>
                        <div class="contact-details">
                            <div class="contact-detail-item">
                                <strong>E-mail</strong>
                                <span>kwg0825&#64;naver.com</span>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-4 mb-4">
                    <div class="contact-method">
                        <div class="method-icon">
                            <i class="nc-icon nc-pin-3"></i>
                        </div>
                        <h4>방문 상담</h4>
                        <p>직접 방문하여 상담받으실 수 있습니다</p>
                        <div class="contact-details">
                            <div class="contact-detail-item">
                                <strong>주소</strong>
                                <span class="address-text">인천광역시 서구 마중로142<br>나동 5호 (오류동)</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 기타 정보 섹션 -->
    <div class="section section-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2 class="title">추가 정보</h2>
                    <h5 class="description">수인산업에 대한 더 많은 정보를 확인하세요</h5>
                    <div class="separator-line-light"></div>
                    
                    <div class="additional-info mt-5">
                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="info-showcase">
                                    <img src="assets/img/general/misc-2.png" alt="회사 정보" class="img-fluid rounded">
                                    <h5 class="mt-3">회사 소개서</h5>
                                    <p>상세한 회사 정보 확인</p>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="info-showcase">
                                    <img src="assets/img/general/misc-3.png" alt="제품 카탈로그" class="img-fluid rounded">
                                    <h5 class="mt-3">제품 카탈로그</h5>
                                    <p>전체 제품 라인업 보기</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="final-cta mt-5">
                        <a href="/products" class="btn btn-danger btn-round btn-lg mr-3">
                            <i class="nc-icon nc-app"></i>
                            제품 보기
                        </a>
                        <a href="/about-us" class="btn btn-outline-light btn-round btn-lg">
                            <i class="nc-icon nc-building"></i>
                            회사 소개
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// sooindustry-react/src/app/customer-support/page.tsx
import {
  additionalResources,
  companyFacts,
  contactMethods,
  customerPartners,
  quickActions,
} from "@/data/customerSupport";

export default function CustomerSupportPage() {
  return (
    <div className="wrapper">
      <div
        className="page-header page-header-xs"
        style={{ backgroundImage: "url('/img/general/misc-1.jpg')" }}
        data-parallax="true"
      >
        <div className="filter" />
        <div className="content-center">
          <div className="container">
            <h1 className="title">연락처 및 고객지원</h1>
            <h4 className="description">수인산업과 함께하세요</h4>
          </div>
        </div>
      </div>

      <div className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center mb-5">
              <h2 className="title">연락처 정보</h2>
              <h5 className="description">수인산업에 언제든지 문의해 주세요</h5>
              <div className="separator-line" />
            </div>
          </div>

          <div className="row align-items-center">
            <div className="col-md-6 mb-4">
              <div className="company-info-card">
                <div className="card-header">
                  <h3 className="company-title">
                    <i className="nc-icon nc-bank" aria-hidden="true" />
                    수인산업
                  </h3>
                </div>
                <div className="card-body">
                  <div className="contact-info">
                    {companyFacts.map((fact) => (
                      <div key={fact.label} className="contact-item">
                        <div className="contact-icon">
                          <i className={`nc-icon ${fact.icon}`} aria-hidden="true" />
                        </div>
                        <div className="contact-content">
                          <strong>{fact.label}</strong>
                          <span>{fact.value}</span>
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="quick-contact-buttons mt-4">
                    {quickActions.map((action) => (
                      <button key={action.label} type="button" className={action.classes}>
                        <i className={`nc-icon ${action.icon}`} aria-hidden="true" />
                        {action.label}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="col-md-6">
              <div className="contact-image-wrapper">
                <img
                  src="/img/general/customer-card.png"
                  alt="고객관리카드"
                  className="img-fluid rounded shadow"
                  loading="lazy"
                />
                <div className="image-overlay">
                  <div className="overlay-text">
                    <i className="nc-icon nc-check-2" aria-hidden="true" />
                    <p>체계적인 고객 관리</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="section section-light">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center mb-5">
              <h2 className="title">주요 고객사</h2>
              <h5 className="description">신뢰할 수 있는 파트너십</h5>
              <div className="separator-line" />
            </div>
          </div>

          <div className="row">
            {customerPartners.map((partner) => (
              <div key={partner.name} className="col-lg-3 col-md-4 col-sm-6 mb-4">
                <div className="customer-card">
                  <div className="customer-icon">
                    <i className={`nc-icon ${partner.icon}`} aria-hidden="true" />
                  </div>
                  <h5>{partner.name}</h5>
                  <p>{partner.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="section">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center mb-5">
              <h2 className="title">문의 방법</h2>
              <h5 className="description">다양한 방법으로 연락하실 수 있습니다</h5>
              <div className="separator-line" />
            </div>
          </div>

          <div className="row">
            {contactMethods.map((method) => (
              <div key={method.title} className="col-md-4 mb-4">
                <div className="contact-method">
                  <div className="method-icon">
                    <i className={`nc-icon ${method.icon}`} aria-hidden="true" />
                  </div>
                  <h4>{method.title}</h4>
                  <p>{method.description}</p>
                  <div className="contact-details">
                    {method.details.map((detail) => (
                      <div key={detail.label} className="contact-detail-item">
                        <strong>{detail.label}</strong>
                        {detail.isHtml ? (
                          <span
                            className="address-text"
                            dangerouslySetInnerHTML={{ __html: detail.value }}
                          />
                        ) : (
                          <span>{detail.value}</span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="section section-dark">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center">
              <h2 className="title">추가 정보</h2>
              <h5 className="description">수인산업에 대한 더 많은 정보를 확인하세요</h5>
              <div className="separator-line-light" />

              <div className="additional-info mt-5">
                <div className="row">
                  {additionalResources.map((resource) => (
                    <div key={resource.title} className="col-md-6 mb-4">
                      <div className="info-showcase">
                        <img src={resource.image} alt={resource.alt} className="img-fluid rounded" loading="lazy" />
                        <h5 className="mt-3">{resource.title}</h5>
                        <p>{resource.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="final-cta mt-5">
                <a href="/products" className="btn btn-danger btn-round btn-lg mr-3">
                  <i className="nc-icon nc-app" aria-hidden="true" />
                  제품 보기
                </a>
                <a href="/about-us" className="btn btn-outline-light btn-round btn-lg">
                  <i className="nc-icon nc-bank" aria-hidden="true" />
                  회사 소개
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
